# Generated by Django 3.2.9 on 2022-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='discotecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('foto', models.TextField()),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
