# Generated by Django 3.2.9 on 2022-02-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addticket', '0002_discotecas'),
    ]

    operations = [
        migrations.AddField(
            model_name='addticket',
            name='dia',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='addticket',
            name='mes',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='addticket',
            name='precio',
            field=models.FloatField(null=True),
        ),
    ]
