# Generated by Django 3.2.9 on 2022-02-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addticket', '0003_auto_20220217_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='addticket',
            name='ciudad',
            field=models.TextField(default='Prueba'),
        ),
    ]
