# Generated by Django 3.2.9 on 2022-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addticket', '0004_addticket_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='addticket',
            name='instagram',
            field=models.TextField(default='@tu_instagram'),
        ),
    ]
