# Generated by Django 3.2.9 on 2022-02-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addticket', '0005_addticket_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='addticket',
            name='n_tel_comp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addticket',
            name='n_tel_vend',
            field=models.IntegerField(default=0),
        ),
    ]
