# Generated by Django 3.2.9 on 2022-02-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addticket', '0006_auto_20220220_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addticket',
            name='n_tel_comp',
            field=models.CharField(default='000000000', max_length=9),
        ),
        migrations.AlterField(
            model_name='addticket',
            name='n_tel_vend',
            field=models.CharField(default='000000000', max_length=9),
        ),
    ]
