# Generated by Django 3.2.9 on 2022-02-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addticket', '0007_auto_20220220_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addticket',
            name='ciudad',
            field=models.TextField(default='Prueba', max_length=20),
        ),
        migrations.AlterField(
            model_name='addticket',
            name='instagram',
            field=models.TextField(default='@tu_instagram', max_length=20),
        ),
    ]
